import type { Reward } from '../types/reward';

export const REWARD_POOL: Reward[] = [
  {
    id: 'crimson-focus',
    name: '赤焰聚焦',
    description: '所有防御塔伤害提升 15%，红塔额外再提升 10%。',
    rarity: 'common',
    type: 'damage',
    effect: {
      towerDamageMultiplier: 1.15,
      towerTypeDamageBonus: { red: 0.1 },
    },
    buildStatDeltas: { redPower: 2 },
    tags: ['火焰强化流'],
  },
  {
    id: 'expanding-sketch',
    name: '延展笔触',
    description: '所有防御塔攻击范围 +0.45。',
    rarity: 'common',
    type: 'range',
    effect: {
      towerRangeBonus: 0.45,
    },
    buildStatDeltas: { defense: 1, fusion: 1 },
    tags: ['阵地扩张流'],
  },
  {
    id: 'rapid-strokes',
    name: '疾速连描',
    description: '所有防御塔攻速提升 12%，黄塔额外再提升 8%。',
    rarity: 'rare',
    type: 'attackSpeed',
    effect: {
      towerAttackSpeedMultiplier: 0.88,
      towerTypeAttackSpeedMultiplier: { yellow: 0.92 },
    },
    buildStatDeltas: { yellowSpeed: 2 },
    tags: ['高速连射流'],
  },
  {
    id: 'ink-dividend',
    name: '颜料分红',
    description: '击杀敌人额外获得 4 点对应颜料。',
    rarity: 'common',
    type: 'economy',
    effect: {
      bonusPaintOnKill: 4,
    },
    buildStatDeltas: { economy: 2 },
    tags: ['颜料经济流'],
  },
  {
    id: 'storm-pigment',
    name: '疾风颜流',
    description: '子弹速度提升 28%。',
    rarity: 'rare',
    type: 'projectile',
    effect: {
      projectileSpeedMultiplier: 1.28,
    },
    buildStatDeltas: { yellowSpeed: 1, fusion: 1 },
    tags: ['高速连射流'],
  },
  {
    id: 'restoration-frame',
    name: '修复画框',
    description: '立刻恢复 20 点核心生命值。',
    rarity: 'epic',
    type: 'healing',
    effect: {
      coreHealthRestore: 20,
    },
    buildStatDeltas: { defense: 3 },
    tags: ['核心防御流'],
  },
  {
    id: 'frost-resonance',
    name: '寒色共振',
    description: '蓝塔伤害提升 15%，攻击范围额外 +0.3。',
    rarity: 'rare',
    type: 'special',
    effect: {
      towerTypeDamageBonus: { blue: 0.15 },
      towerTypeRangeBonus: { blue: 0.3 },
    },
    buildStatDeltas: { blueControl: 3 },
    tags: ['控制冻结流'],
  },
  {
    id: 'solar-burst',
    name: '耀光突刺',
    description: '黄塔伤害提升 12%，额外发射 1 枚分裂弹。',
    rarity: 'epic',
    type: 'special',
    effect: {
      towerTypeDamageBonus: { yellow: 0.12 },
      splitShots: 1,
    },
    buildStatDeltas: { yellowSpeed: 2, fusion: 1 },
    tags: ['高速连射流'],
  },
  {
    id: 'prismatic-echo',
    name: '棱彩回响',
    description: '解锁棱彩回响，所有子弹可额外命中 1 个目标，并略微提升伤害。',
    rarity: 'legendary',
    type: 'unlock',
    effect: {
      unlockSpecial: '棱彩回响',
      chainHits: 1,
      towerDamageMultiplier: 1.08,
    },
    buildStatDeltas: { redPower: 1, blueControl: 1, yellowSpeed: 1, fusion: 3 },
    tags: ['三色融合流'],
  },
  {
    id: 'grand-mosaic',
    name: '大地拼彩',
    description: '所有防御塔伤害提升 8%，范围 +0.2，攻速提升 6%。',
    rarity: 'legendary',
    type: 'special',
    effect: {
      towerDamageMultiplier: 1.08,
      towerRangeBonus: 0.2,
      towerAttackSpeedMultiplier: 0.94,
    },
    buildStatDeltas: {
      redPower: 1,
      blueControl: 1,
      yellowSpeed: 1,
      economy: 1,
      defense: 1,
      fusion: 2,
    },
    tags: ['三色融合流'],
  },
];
